// @routes-hash 927957d5db07dde797db92df9101a55b
import { Express } from "express";

import route1 from "./routes/assets/addAssets";
import route2 from "./routes/assets/delAssets";
import route3 from "./routes/assets/delAssetsImage";
import route4 from "./routes/assets/generateAssets";
import route5 from "./routes/assets/getAssets";
import route6 from "./routes/assets/getImage";
import route7 from "./routes/assets/getStoryboard";
import route8 from "./routes/assets/polishPrompt";
import route9 from "./routes/assets/saveAssets";
import route10 from "./routes/assets/updateAssets";
import route11 from "./routes/index/index";
import route12 from "./routes/novel/addNovel";
import route13 from "./routes/novel/delNovel";
import route14 from "./routes/novel/getNovel";
import route15 from "./routes/novel/updateNovel";
import route16 from "./routes/other/clearDatabase";
import route17 from "./routes/other/deleteAllData";
import route18 from "./routes/other/getCaptcha";
import route19 from "./routes/other/getModels";
import route20 from "./routes/other/login";
import route21 from "./routes/other/testAI";
import route22 from "./routes/other/testImage";
import route23 from "./routes/other/testVideo";
import route24 from "./routes/outline/addOutline";
import route25 from "./routes/outline/agentsOutline";
import route26 from "./routes/outline/delOutline";
import route27 from "./routes/outline/getHistory";
import route28 from "./routes/outline/getOutline";
import route29 from "./routes/outline/getPartScript";
import route30 from "./routes/outline/getStoryline";
import route31 from "./routes/outline/setHistory";
import route32 from "./routes/outline/updateOutline";
import route33 from "./routes/outline/updateScript";
import route34 from "./routes/outline/updateStoryline";
import route35 from "./routes/poetry_assets/addAssets";
import route36 from "./routes/poetry_assets/delAssets";
import route37 from "./routes/poetry_assets/delAssetsImage";
import route38 from "./routes/poetry_assets/generateAssets";
import route39 from "./routes/poetry_assets/getAssets";
import route40 from "./routes/poetry_assets/getImage";
import route41 from "./routes/poetry_assets/getStoryboard";
import route42 from "./routes/poetry_assets/polishPrompt";
import route43 from "./routes/poetry_assets/saveAssets";
import route44 from "./routes/poetry_assets/updateAssets";
import route45 from "./routes/poetry_novel/addNovel";
import route46 from "./routes/poetry_novel/delNovel";
import route47 from "./routes/poetry_novel/getNovel";
import route48 from "./routes/poetry_novel/updateNovel";
import route49 from "./routes/poetry_outline/addOutline";
import route50 from "./routes/poetry_outline/agentsOutline";
import route51 from "./routes/poetry_outline/delOutline";
import route52 from "./routes/poetry_outline/getHistory";
import route53 from "./routes/poetry_outline/getOutline";
import route54 from "./routes/poetry_outline/getPartScript";
import route55 from "./routes/poetry_outline/getStoryline";
import route56 from "./routes/poetry_outline/setHistory";
import route57 from "./routes/poetry_outline/updateOutline";
import route58 from "./routes/poetry_outline/updateScript";
import route59 from "./routes/poetry_outline/updateStoryline";
import route60 from "./routes/poetry_script/generateScriptApi";
import route61 from "./routes/poetry_script/generateScriptSave";
import route62 from "./routes/poetry_script/geScriptApi";
import route63 from "./routes/poetry_storyboard/batchSuperScoreImage";
import route64 from "./routes/poetry_storyboard/chatStoryboard";
import route65 from "./routes/poetry_storyboard/delStoryboard";
import route66 from "./routes/poetry_storyboard/generateShotImage";
import route67 from "./routes/poetry_storyboard/generateStoryboardApi";
import route68 from "./routes/poetry_storyboard/generateVideoPrompt";
import route69 from "./routes/poetry_storyboard/getStoryboard";
import route70 from "./routes/poetry_storyboard/keepStoryboard";
import route71 from "./routes/poetry_storyboard/saveStoryboard";
import route72 from "./routes/poetry_storyboard/uploadImage";
import route73 from "./routes/poetry_video/addVideo";
import route74 from "./routes/poetry_video/addVideoConfig";
import route75 from "./routes/poetry_video/deleteVideoConfig";
import route76 from "./routes/poetry_video/generatePrompt";
import route77 from "./routes/poetry_video/generateVideo";
import route78 from "./routes/poetry_video/getManufacturer";
import route79 from "./routes/poetry_video/getVideo";
import route80 from "./routes/poetry_video/getVideoConfigs";
import route81 from "./routes/poetry_video/getVideoModel";
import route82 from "./routes/poetry_video/getVideoStoryboards";
import route83 from "./routes/poetry_video/reviseVideoStoryboards";
import route84 from "./routes/poetry_video/saveVideo";
import route85 from "./routes/poetry_video/upDateVideoConfig";
import route86 from "./routes/poetry/index";
import route87 from "./routes/project/addProject";
import route88 from "./routes/project/delProject";
import route89 from "./routes/project/getProject";
import route90 from "./routes/project/getProjectCount";
import route91 from "./routes/project/getSingleProject";
import route92 from "./routes/project/updateProject";
import route93 from "./routes/prompt/getPrompts";
import route94 from "./routes/prompt/updatePrompt";
import route95 from "./routes/script/generateScriptApi";
import route96 from "./routes/script/generateScriptSave";
import route97 from "./routes/script/geScriptApi";
import route98 from "./routes/setting/addModel";
import route99 from "./routes/setting/configurationModel";
import route100 from "./routes/setting/delModel";
import route101 from "./routes/setting/getAiModelList";
import route102 from "./routes/setting/getAiModelMap";
import route103 from "./routes/setting/getLog";
import route104 from "./routes/setting/getSetting";
import route105 from "./routes/setting/getVideoModelDetail";
import route106 from "./routes/setting/getVideoModelList";
import route107 from "./routes/setting/updateModel";
import route108 from "./routes/setting/updeteModel";
import route109 from "./routes/storyboard/batchSuperScoreImage";
import route110 from "./routes/storyboard/chatStoryboard";
import route111 from "./routes/storyboard/delStoryboard";
import route112 from "./routes/storyboard/generateShotImage";
import route113 from "./routes/storyboard/generateStoryboardApi";
import route114 from "./routes/storyboard/generateVideoPrompt";
import route115 from "./routes/storyboard/getStoryboard";
import route116 from "./routes/storyboard/keepStoryboard";
import route117 from "./routes/storyboard/saveStoryboard";
import route118 from "./routes/storyboard/uploadImage";
import route119 from "./routes/task/getTaskApi";
import route120 from "./routes/task/taskDetails";
import route121 from "./routes/user/getUser";
import route122 from "./routes/user/saveUser";
import route123 from "./routes/video/addVideo";
import route124 from "./routes/video/addVideoConfig";
import route125 from "./routes/video/deleteVideoConfig";
import route126 from "./routes/video/generatePrompt";
import route127 from "./routes/video/generateVideo";
import route128 from "./routes/video/getManufacturer";
import route129 from "./routes/video/getVideo";
import route130 from "./routes/video/getVideoConfigs";
import route131 from "./routes/video/getVideoModel";
import route132 from "./routes/video/getVideoStoryboards";
import route133 from "./routes/video/reviseVideoStoryboards";
import route134 from "./routes/video/saveVideo";
import route135 from "./routes/video/upDateVideoConfig";

export default async (app: Express) => {
  app.use("/assets/addAssets", route1);
  app.use("/assets/delAssets", route2);
  app.use("/assets/delAssetsImage", route3);
  app.use("/assets/generateAssets", route4);
  app.use("/assets/getAssets", route5);
  app.use("/assets/getImage", route6);
  app.use("/assets/getStoryboard", route7);
  app.use("/assets/polishPrompt", route8);
  app.use("/assets/saveAssets", route9);
  app.use("/assets/updateAssets", route10);
  app.use("/index", route11);
  app.use("/novel/addNovel", route12);
  app.use("/novel/delNovel", route13);
  app.use("/novel/getNovel", route14);
  app.use("/novel/updateNovel", route15);
  app.use("/other/clearDatabase", route16);
  app.use("/other/deleteAllData", route17);
  app.use("/other/getCaptcha", route18);
  app.use("/other/getModels", route19);
  app.use("/other/login", route20);
  app.use("/other/testAI", route21);
  app.use("/other/testImage", route22);
  app.use("/other/testVideo", route23);
  app.use("/outline/addOutline", route24);
  app.use("/outline/agentsOutline", route25);
  app.use("/outline/delOutline", route26);
  app.use("/outline/getHistory", route27);
  app.use("/outline/getOutline", route28);
  app.use("/outline/getPartScript", route29);
  app.use("/outline/getStoryline", route30);
  app.use("/outline/setHistory", route31);
  app.use("/outline/updateOutline", route32);
  app.use("/outline/updateScript", route33);
  app.use("/outline/updateStoryline", route34);
  app.use("/poetry_assets/addAssets", route35);
  app.use("/poetry_assets/delAssets", route36);
  app.use("/poetry_assets/delAssetsImage", route37);
  app.use("/poetry_assets/generateAssets", route38);
  app.use("/poetry_assets/getAssets", route39);
  app.use("/poetry_assets/getImage", route40);
  app.use("/poetry_assets/getStoryboard", route41);
  app.use("/poetry_assets/polishPrompt", route42);
  app.use("/poetry_assets/saveAssets", route43);
  app.use("/poetry_assets/updateAssets", route44);
  app.use("/poetry_novel/addNovel", route45);
  app.use("/poetry_novel/delNovel", route46);
  app.use("/poetry_novel/getNovel", route47);
  app.use("/poetry_novel/updateNovel", route48);
  app.use("/poetry_outline/addOutline", route49);
  app.use("/poetry_outline/agentsOutline", route50);
  app.use("/poetry_outline/delOutline", route51);
  app.use("/poetry_outline/getHistory", route52);
  app.use("/poetry_outline/getOutline", route53);
  app.use("/poetry_outline/getPartScript", route54);
  app.use("/poetry_outline/getStoryline", route55);
  app.use("/poetry_outline/setHistory", route56);
  app.use("/poetry_outline/updateOutline", route57);
  app.use("/poetry_outline/updateScript", route58);
  app.use("/poetry_outline/updateStoryline", route59);
  app.use("/poetry_script/generateScriptApi", route60);
  app.use("/poetry_script/generateScriptSave", route61);
  app.use("/poetry_script/geScriptApi", route62);
  app.use("/poetry_storyboard/batchSuperScoreImage", route63);
  app.use("/poetry_storyboard/chatStoryboard", route64);
  app.use("/poetry_storyboard/delStoryboard", route65);
  app.use("/poetry_storyboard/generateShotImage", route66);
  app.use("/poetry_storyboard/generateStoryboardApi", route67);
  app.use("/poetry_storyboard/generateVideoPrompt", route68);
  app.use("/poetry_storyboard/getStoryboard", route69);
  app.use("/poetry_storyboard/keepStoryboard", route70);
  app.use("/poetry_storyboard/saveStoryboard", route71);
  app.use("/poetry_storyboard/uploadImage", route72);
  app.use("/poetry_video/addVideo", route73);
  app.use("/poetry_video/addVideoConfig", route74);
  app.use("/poetry_video/deleteVideoConfig", route75);
  app.use("/poetry_video/generatePrompt", route76);
  app.use("/poetry_video/generateVideo", route77);
  app.use("/poetry_video/getManufacturer", route78);
  app.use("/poetry_video/getVideo", route79);
  app.use("/poetry_video/getVideoConfigs", route80);
  app.use("/poetry_video/getVideoModel", route81);
  app.use("/poetry_video/getVideoStoryboards", route82);
  app.use("/poetry_video/reviseVideoStoryboards", route83);
  app.use("/poetry_video/saveVideo", route84);
  app.use("/poetry_video/upDateVideoConfig", route85);
  app.use("/poetry", route86);
  app.use("/project/addProject", route87);
  app.use("/project/delProject", route88);
  app.use("/project/getProject", route89);
  app.use("/project/getProjectCount", route90);
  app.use("/project/getSingleProject", route91);
  app.use("/project/updateProject", route92);
  app.use("/prompt/getPrompts", route93);
  app.use("/prompt/updatePrompt", route94);
  app.use("/script/generateScriptApi", route95);
  app.use("/script/generateScriptSave", route96);
  app.use("/script/geScriptApi", route97);
  app.use("/setting/addModel", route98);
  app.use("/setting/configurationModel", route99);
  app.use("/setting/delModel", route100);
  app.use("/setting/getAiModelList", route101);
  app.use("/setting/getAiModelMap", route102);
  app.use("/setting/getLog", route103);
  app.use("/setting/getSetting", route104);
  app.use("/setting/getVideoModelDetail", route105);
  app.use("/setting/getVideoModelList", route106);
  app.use("/setting/updateModel", route107);
  app.use("/setting/updeteModel", route108);
  app.use("/storyboard/batchSuperScoreImage", route109);
  app.use("/storyboard/chatStoryboard", route110);
  app.use("/storyboard/delStoryboard", route111);
  app.use("/storyboard/generateShotImage", route112);
  app.use("/storyboard/generateStoryboardApi", route113);
  app.use("/storyboard/generateVideoPrompt", route114);
  app.use("/storyboard/getStoryboard", route115);
  app.use("/storyboard/keepStoryboard", route116);
  app.use("/storyboard/saveStoryboard", route117);
  app.use("/storyboard/uploadImage", route118);
  app.use("/task/getTaskApi", route119);
  app.use("/task/taskDetails", route120);
  app.use("/user/getUser", route121);
  app.use("/user/saveUser", route122);
  app.use("/video/addVideo", route123);
  app.use("/video/addVideoConfig", route124);
  app.use("/video/deleteVideoConfig", route125);
  app.use("/video/generatePrompt", route126);
  app.use("/video/generateVideo", route127);
  app.use("/video/getManufacturer", route128);
  app.use("/video/getVideo", route129);
  app.use("/video/getVideoConfigs", route130);
  app.use("/video/getVideoModel", route131);
  app.use("/video/getVideoStoryboards", route132);
  app.use("/video/reviseVideoStoryboards", route133);
  app.use("/video/saveVideo", route134);
  app.use("/video/upDateVideoConfig", route135);
}
